spring:
  application:
    name: PASSBOOK-GATEWAY
  cloud:
    gateway:
      routes:
        - id: merchant-service
          uri: lb://MERCHANT-SERVICE:9527/
          predicates:
            - Path=/merchants/**
#          filters:
#            - AuthCheckFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8989